version: '3.9'

services:

    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
            - "27017:27017"
        restart: unless-stopped
        volumes:
            - mongodb-data:/data/db
        networks:
            - mongodb_network
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
            interval: 30s
            timeout: 10s
            retries: 3

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin123
        volumes:
            - mongodb-data
        depends_on:
            - mongodb
        networks:
            - mongodb_network
        ports:
            - "8081:8081"
        healthcheck:
            test: wget --quiet --tries=3 --spider http://admin:admin123@10.10.10.60:8081 || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
        restart: unless-stopped

volumes:
    mongodb-data:
        name: mongodb-data
networks:
    mongodb_network:
        name: mongodb_network
